Problem 1: The Matrix Architect
Task: 1. Create a 2D NumPy array with 5 rows and 3 columns filled entirely with the number 7. 2. Change the element in the third row, second column to 10. 3. Print the following attributes of the array: ndim, shape, and dtype.

In [ ]:
import numpy as np
matrix = np.full((5,3), 7)
matrix[2,1] = 10
print(matrix.ndim)
print(matrix.dtype)
print(matrix.shape)

2
int32
[[ 7  7  7]
 [ 7  7  7]
 [ 7 10  7]
 [ 7  7  7]
 [ 7  7  7]]


Problem 2: The Linear Navigator
Task: 1. Create a 1D array called evens that contains all even integers from 10 to 50 (inclusive). 2. Create a second 1D array called linspace_data that contains 15 equally spaced values between 0 and 100. 3. Calculate and print the total memory size (in bytes) of the evens array.
Hint: Total bytes = .size multiplied by .itemsize.



In [3]:
evens = np.arange(10,50,2)
linespace_data = np.linspace(0,100,15)

print(evens.size*evens.itemsize)

80



Problem 3: The 3D Tensor Check
Task: Imagine you are storing data for a 3-day experiment. Each day, you take 4 readings from 2 different sensors.
Create a 3D array of zeros with the shape (3, 4, 2) to represent this data.

Print the size of the array.

Verify the "Rank" of the array by printing its ndim.

Explain in a comment what each number in the shape (3, 4, 2) represents based on the experiment description.

In [ ]:
experiment_data = np.zeros((3,4,2))
print(experiment_data.size)
print(experiment_data.ndim)
#3 days 4 readings 2 sensors makes the (3, 4, 2) shape

24
3
