Problem 1: The Multi-Dimensional Sensor Grid Scenario: You have a 3D array representing temperature readings from a grid of sensors over time.

Structure: (4 days, 5 sensors per row, 2 rows of sensors).

Data: data = np.random.randint(20, 45, (4, 5, 2))

Task:

Calculate the daily average temperature for the entire grid.

Find the highest temperature recorded for each specific sensor across the 4-day period.

Determine the variance of temperatures for each row of sensors, averaged over the 4 days.

In [13]:
import numpy as np

data = np.random.randint(20, 45, (4, 5, 2))
print(data)
print(data.mean(axis=(1,2)))
print(data.max(axis=(0)))
print(data.var(axis=1).mean(axis=0))

[[[23 28]
  [31 22]
  [28 22]
  [23 29]
  [35 31]]

 [[41 26]
  [28 29]
  [35 40]
  [33 32]
  [30 43]]

 [[20 31]
  [40 40]
  [37 22]
  [44 40]
  [38 34]]

 [[23 37]
  [32 34]
  [36 21]
  [32 21]
  [38 41]]]
[27.2 33.7 34.6 31.5]
[[41 37]
 [40 40]
 [37 40]
 [44 40]
 [38 43]]
[34.14 42.36]


Problem 2: Global Sales Normalization Scenario: You have a 2D array sales of shape (10, 3), where rows are different products and columns are sales in 3 different regions.

Create this array with random integers between 100 and 1000.

Normalize the data: Subtract the mean of each product from its sales across all regions, and then divide by the standard deviation of that specific product.

Verify that the new mean for each product row is approximately 0 and the standard deviation is 1. Note: This must be done entirely through broadcasting.

In [22]:
data = np.random.randint(100, 1000, (10,3))
print(data)
normalized_data = (data - np.mean(data,axis=1,keepdims=True)) / np.std(data,axis=1,keepdims=True)
print(normalized_data)
print(np.mean(normalized_data,axis=1))
print(np.std(normalized_data,axis=1))

[[729 749 401]
 [807 460 332]
 [769 114 803]
 [951 938 803]
 [129 528 775]
 [996 968 859]
 [806 993 458]
 [743 748 748]
 [558 163 456]
 [822 824 469]]
[[ 0.64350147  0.7688589  -1.41236038]
 [ 1.36542213 -0.36378035 -1.00164178]
 [ 0.65281605 -1.41285793  0.76004188]
 [ 0.80201803  0.60774037 -1.40975839]
 [-1.30878208  0.1903683   1.11841378]
 [ 0.93064515  0.45686217 -1.38750732]
 [ 0.24208528  1.08562469 -1.32770997]
 [-1.41421356  0.70710678  0.70710678]
 [ 0.98950205 -1.36977346  0.38027141]
 [ 0.70110596  0.71309068 -1.41419663]]
[-2.22044605e-16 -7.40148683e-17  3.70074342e-17 -5.92118946e-16
  0.00000000e+00  0.00000000e+00 -1.48029737e-16 -1.60612264e-14
  1.11022302e-16  0.00000000e+00]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Problem 3: The Geometric TransformationScenario: You are given a set of 2D coordinates representing the corners of a 

square.coords = np.array([[0, 0], [0, 1], [1, 1], [1, 0]])Use broadcasting to shift the square 5 units to the right and 3 units up.Use a ufunc to scale the coordinates by a factor of 2.5 relative to the origin.
Calculate the Euclidean distance of each transformed coordinate from the origin (0.0) without using a loop.

In [27]:
coords = np.array([[0, 0], [0, 1], [1, 1], [1, 0]])
coords[:, 0]+=3
coords[:, 1]+=5
print(coords)
coords = np.multiply(coords,2.5)
print(coords)
distances = coords[:,0]**2 + coords[:,1]**2
print(distances)

[[3 5]
 [3 6]
 [4 6]
 [4 5]]
[[ 7.5 12.5]
 [ 7.5 15. ]
 [10.  15. ]
 [10.  12.5]]
[212.5  281.25 325.   256.25]


Problem 4: Conditional Quality Control Scenario: A factory produces metal rods. You have an array of lengths (in cm):

rods = np.array([10.1, 9.8, 10.5, 10.0, 9.9, 10.2, 11.0, 9.0, 10.1, 10.0])

Calculate the mean and standard deviation of the batch.

A rod is considered "Defective" if it is more than 2 standard deviations away from the mean.

Use aggregations and boolean logic to find the percentage of defective rods in this batch.



In [34]:
rods = np.array([10.1, 9.8, 10.5, 10.0, 9.9, 10.2, 11.0, 9.0, 10.1, 10.0])
mean = rods.mean()
std = rods.std()
defective = (rods >= mean - 2*std) & (rods <= mean + 2*std)
print(np.sum(defective)/len(defective)*100,'%')

90.0 %


Problem 5: The Weighted GPA Calculator Scenario: A student has taken 5 courses with different credit weights.

grades = np.array([85, 92, 78, 88, 95])

weights = np.array([3, 4, 3, 2, 5])

Calculate the weighted average of the grades using NumPy ufuncs.

If the student receives a "bonus" of 5 points on every grade where they scored below 90, update the grades array.

Re-calculate the new weighted average after the bonus.

In [38]:
grades = np.array([85, 92, 78, 88, 95])

weights = np.array([3, 4, 3, 2, 5])

weighted_avg = np.sum(grades * weights) / np.sum(weights)
print(weighted_avg)

grades[grades<90] += 5

bonus_weighted_avg = np.sum(grades * weights) / np.sum(weights)
print(bonus_weighted_avg)

88.70588235294117
91.05882352941177
